name: Check Appointments with Chrome Headless

on:
  schedule:
    - cron: '*/10 * * * *'  # Runs every 3 Minutes
  workflow_dispatch:    # Allows manual trigger of the workflow

jobs:
  check-appointments:
    runs-on: ubuntu-latest

    env:
      TELEGRAM_BOT_SECRET: ${{ secrets.TELEGRAM_BOT_SECRET }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip
      - name: Install Chrome
        run: |
          wget -q -O google-chrome-stable_current_amd64.deb https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo dpkg -i google-chrome-stable_current_amd64.deb || sudo apt-get -f install -y
      - name: Install ChromeDriver
        run: |
          echo "Installing ChromeDriver"
          CHROME_VERSION=$(google-chrome --version | grep -oP '\d+\.\d+\.\d+\.\d+' | cut -d '.' -f 1,2,3)
          echo "Detected Chrome version: $CHROME_VERSION"
          CHROMEDRIVER_VERSION=$(curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION")
          echo "Detected ChromeDriver version: $CHROMEDRIVER_VERSION"
          wget -q https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/chromedriver
          sudo chmod +x /usr/local/bin/chromedriver
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests selenium
      - name: Run script
        run: |
          python termin.py
