name: Check Appointments with Firefox

on:
  schedule:
    - cron: '*/3 * * * *'  # Runs every 3 Minutes
  workflow_dispatch:    # Allows manual trigger of the workflow

jobs:
  check-appointments:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install Firefox and GeckoDriver
        run: |
          sudo apt-get update
          sudo apt-get install -y firefox
          wget https://github.com/mozilla/geckodriver/releases/download/v0.29.0/geckodriver-v0.29.0-linux64.tar.gz
          tar -xzf geckodriver-v0.29.0-linux64.tar.gz
          sudo mv geckodriver /usr/bin/geckodriver
          sudo chmod +x /usr/bin/geckodriver
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests selenium
      - name: Run script
        run: |
          python termin.py
